import { createClient } from "@/lib/supabase/server"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Building2, ShoppingCart, TrendingDown, Wallet } from "lucide-react"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export default async function IndustryDashboardPage() {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  const { data: profile } = await supabase
    .from("profiles")
    .select("*")
    .eq("id", user!.id)
    .single()

  return (
    <div className="flex flex-col gap-8">
      <div className="flex flex-col gap-2">
        <div className="flex items-center gap-3">
          <h1 className="text-3xl font-bold text-foreground">
            {profile?.company_name || "Industry Dashboard"}
          </h1>
          <Badge variant="secondary">Industry</Badge>
        </div>
        <p className="text-muted-foreground">
          Browse and purchase verified carbon credits to offset your emissions.
        </p>
      </div>

      {/* Stats Overview */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Credits Purchased</CardTitle>
            <ShoppingCart className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-foreground">0</div>
            <p className="text-xs text-muted-foreground mt-1">Total credits bought</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Carbon Offset</CardTitle>
            <TrendingDown className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-foreground">0 kg</div>
            <p className="text-xs text-muted-foreground mt-1">{"CO\u2082 emissions offset"}</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Credits Retired</CardTitle>
            <Building2 className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-foreground">0</div>
            <p className="text-xs text-muted-foreground mt-1">Permanently retired</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Total Spent</CardTitle>
            <Wallet className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-foreground">$0.00</div>
            <p className="text-xs text-muted-foreground mt-1">On carbon credits</p>
          </CardContent>
        </Card>
      </div>

      {/* Quick Actions */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Carbon Credit Marketplace</CardTitle>
            <CardDescription>
              Browse verified carbon credits generated by individuals through sustainable activities like EV usage and solar energy generation.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Link href="/industry/marketplace">
              <Button className="w-full">
                <ShoppingCart className="w-4 h-4 mr-2" />
                Browse Credits
              </Button>
            </Link>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Your Portfolio</CardTitle>
            <CardDescription>
              View your purchased credits, retirement history, and track your progress towards ESG and sustainability goals.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Link href="/industry/portfolio">
              <Button variant="outline" className="w-full bg-transparent">
                <Building2 className="w-4 h-4 mr-2" />
                View Portfolio
              </Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
